# Generated by Django 4.0.4 on 2022-06-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeenotesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
